#ifndef INCLUDE_COMMON_H
#define INCLUDE_COMMON_H

#include <ch.h>
#include <hal.h>

#define PROGRAM_ROUTINE_MASTER 0
#define PROGRAM_ROUTINE_TEST_PWM 1

#define MAIN_PROGRAM_ROUTINE PROGRAM_ROUTINE_TEST_PWM

#endif
